import { createPagesFunctionHandler } from "@react-router/cloudflare";
import type { ServerBuild } from "react-router";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as buildImport from "../build/server";

const build = buildImport as unknown as ServerBuild;

export const onRequest = createPagesFunctionHandler({
  build,
} as {
  build: ServerBuild;
  getLoadContext: any;
});
